title: Bailey Pages
description: "Bailey's GitHub Playground"
owner_name: Bailey Leeder
github_username: Bloooooooooob
github_repo: "Bailey-GitHub-Playground" 
baseurl: "/Bailey-GitHub-Playground"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/nighthawkcoders"}
    - { platform: x, user_url: "https://x.com/NighthawkCoding/" }
    - { platform: youtube, user_url: "https://www.youtube.com/@nighthawkcodingsociety2868" } 
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/game.md
  - navigation/blog.md
  - navigation/game.md
  - navigation/about.md
  - README4YML.md

